before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install libfontconfig1
  - npm install -g karma-cli
  - npm install npm@latest -g
  - npm install -g bower
  - bower install -f

language: node_js
node_js:
 - 4.2.4
