before_script:
  - sudo apt-get install libfontconfig1
  - npm install -g karma-cli
  - npm config set -g production false
  - npm install npm@latest -g
  - npm install -g bower
  - bower install -f

language: node_js
node_js:
 - 4.2.4
